/**
 * Generate Question Tool - Phase G Stage 39
 * 
 * Generates formative assessment questions for a specific concept.
 * AI specifies concept, difficulty, format, and targeted misconception.
 * Separate: generation → validation → evidence creation.
 * 
 * Deterministic validation where possible (math expressions can be evaluated).
 * AI validation where necessary (open-ended explanations).
 */

import config from '../config/index.js';

/**
 * Execute question generation
 */
export async function executeGenerateQuestion({
  waxId,
  sessionId,
  concept_tag,
  difficulty = 'medium',
  format = 'multiple_choice',
  targeted_misconception = null,
}) {
  const questionId = crypto.randomUUID();

  try {
    // Generate question (AI-driven - the AI specifies what to generate)
    const question = await generateQuestionContent({
      concept_tag,
      difficulty,
      format,
      targeted_misconception,
    });

    // Validate the generated question
    const validation = validateQuestion(question, format);

    if (!validation.valid) {
      throw new Error(`Question validation failed: ${validation.errors.join(', ')}`);
    }

    // Store question in database
    const storedQuestion = await storeQuestion({
      questionId,
      waxId,
      sessionId,
      concept_tag,
      difficulty,
      format,
      question_text: question.text,
      correct_answer: question.correctAnswer,
      grading_rubric: question.gradingRubric,
    });

    return {
      question_id: storedQuestion.id,
      question_text: question.text,
      question_type: format,
      difficulty,
      correct_answer: question.correctAnswer,
      grading_rubric: question.gradingRubric,
      concept_tag,
      generated_at: new Date().toISOString(),
    };
  } catch (error) {
    console.error('Question generation failed:', error);
    throw error;
  }
}

/**
 * Generate question content (AI-driven)
 */
async function generateQuestionContent({ concept_tag, difficulty, format, targeted_misconception }) {
  // This would integrate with the AI service to generate questions
  // For now, return a structured placeholder that the AI would fill in
  
  return {
    text: `[Question for ${concept_tag} (${difficulty}, ${format}) - TO BE GENERATED BY AI]`,
    correctAnswer: { answer: '[CORRECT_ANSWER_TO_BE_GENERATED_BY_AI]' },
    gradingRubric: {
      criteria: '[GRADING_CRITERIA_TO_BE_GENERATED_BY_AI]',
      points: 10,
    },
  };
}

/**
 * Validate generated question
 */
function validateQuestion(question, format) {
  const errors = [];

  if (!question.text || question.text.length < 10) {
    errors.push('Question text too short');
  }

  if (!question.correctAnswer) {
    errors.push('Missing correct answer');
  }

  if (!question.gradingRubric) {
    errors.push('Missing grading rubric');
  }

  // Validate format-specific requirements
  if (format === 'multiple_choice') {
    if (!question.options || question.options.length < 2) {
      errors.push('Multiple choice questions need at least 2 options');
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}

/**
 * Store question in database
 */
async function storeQuestion({
  questionId,
  waxId,
  sessionId,
  concept_tag,
  difficulty,
  format,
  question_text,
  correct_answer,
  grading_rubric,
}) {
  const result = await db.query(
    `INSERT INTO assessment_questions (
      id, wax_id, session_id, concept_tag, difficulty, format,
      question_text, correct_answer, grading_rubric, created_at
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
    RETURNING id`,
    [
      questionId,
      waxId,
      sessionId,
      concept_tag,
      difficulty,
      format,
      question_text,
      JSON.stringify(correct_answer),
      JSON.stringify(grading_rubric),
    ]
  );

  return { id: result.rows[0].id };
}

export default {
  executeGenerateQuestion,
};
