/**
 * Crisis Protocol - Phase I Stage 46
 * 
 * Deterministic crisis response delivery.
 * 
 * Architecture: Independent detection layer operating in parallel with tutor.
 * 
 * VERA-MH Framework: Target 0.81 clinician alignment. Err toward high recall
 * (accept false positives). False negatives are catastrophic.
 * 
 * Three-Level Response Protocol:
 * - Level 1: Academic Crisis Mention - No action. AI handles naturally.
 * - Level 2: Ambiguous Welfare Signal - Soft check-in.
 * - Level 3: High-Confidence Crisis - DETERMINISTIC response (not AI-generated).
 */

import config from '../../config/index.js';

/**
 * Crisis response levels
 */
export const CrisisLevel = {
  LEVEL_1_ACADEMIC: 1,
  LEVEL_2_AMBIGUOUS: 2,
  LEVEL_3_CRISIS: 3,
};

/**
 * Deterministic crisis response text (NOT AI-generated)
 */
const CRISIS_RESPONSE_TEXT = config.SAFETY_CRISIS_RESPONSE_TEXT;

/**
 * Crisis protocol class
 */
export class CrisisProtocol {
  constructor({ db, logger, emailService = null, webhookService = null }) {
    this.db = db;
    this.logger = logger;
    this.emailService = emailService;
    this.webhookService = webhookService;
  }

  /**
   * Handle a crisis detection
   */
  async handleCrisis({ waxId, sessionId, aiRequestId, level, safetyEventId }) {
    const timestamp = new Date();

    switch (level) {
      case CrisisLevel.LEVEL_1_ACADEMIC:
        return await this.handleLevel1({ waxId, sessionId });

      case CrisisLevel.LEVEL_2_AMBIGUOUS:
        return await this.handleLevel2({ waxId, sessionId, aiRequestId });

      case CrisisLevel.LEVEL_3_CRISIS:
        return await this.handleLevel3({
          waxId,
          sessionId,
          aiRequestId,
          safetyEventId,
        });

      default:
        return { handled: false, reason: 'Unknown crisis level' };
    }
  }

  /**
   * Level 1: Academic mention - no action needed
   */
  async handleLevel1({ waxId, sessionId }) {
    return {
      level: CrisisLevel.LEVEL_1_ACADEMIC,
      action: 'none',
      message: 'Academic mention - no action required',
      crisisResponseDelivered: false,
      operatorNotified: false,
    };
  }

  /**
   * Level 2: Ambiguous welfare signal - soft check-in
   */
  async handleLevel2({ waxId, sessionId, aiRequestId }) {
    const checkInMessage =
      'School can be stressful. If you ever want to talk about something difficult, we are here to listen.';

    // Log the soft check-in
    await this.logCrisisResponse({
      waxId,
      sessionId,
      aiRequestId,
      level: CrisisLevel.LEVEL_2_AMBIGUOUS,
      responseText: checkInMessage,
      deliveredVia: 'whatsapp',
    });

    return {
      level: CrisisLevel.LEVEL_2_AMBIGUOUS,
      action: 'soft_checkin',
      message: checkInMessage,
      crisisResponseDelivered: false,
      operatorNotified: false,
    };
  }

  /**
   * Level 3: High-confidence crisis - DETERMINISTIC response
   * 
   * This is NOT generated by AI. It is a hardcoded, human-reviewed
   * crisis response that must be delivered regardless of AI state.
   */
  async handleLevel3({ waxId, sessionId, aiRequestId, safetyEventId }) {
    const timestamp = new Date();

    // 1. Deliver deterministic crisis response
    const deliverResult = await this.deliverCrisisResponse({
      waxId,
      sessionId,
      aiRequestId,
      text: CRISIS_RESPONSE_TEXT,
    });

    // 2. Notify operator immediately
    const notifyResult = await this.notifyOperator({
      waxId,
      sessionId,
      safetyEventId,
      urgency: 'high',
    });

    // 3. Log the crisis response
    await this.logCrisisResponse({
      waxId,
      sessionId,
      aiRequestId,
      safetyEventId,
      level: CrisisLevel.LEVEL_3_CRISIS,
      responseText: CRISIS_RESPONSE_TEXT,
      deliveredVia: deliverResult.method,
      operatorNotified: notifyResult.notified,
    });

    return {
      level: CrisisLevel.LEVEL_3_CRISIS,
      action: 'crisis_response_delivered',
      message: CRISIS_RESPONSE_TEXT,
      crisisResponseDelivered: true,
      operatorNotified: notifyResult.notified,
      notifyResult,
    };
  }

  /**
   * Deliver deterministic crisis response
   * 
   * CRITICAL: This is infrastructure-level, not AI-generated.
   * Must succeed even if AI or DB is down.
   */
  async deliverCrisisResponse({ waxId, sessionId, aiRequestId, text }) {
    try {
      // Send via WhatsApp
      const result = await this.sendViaWhatsApp({
        waxId,
        message: text,
      });

      return {
        success: true,
        method: 'whatsapp',
        messageId: result.messageId,
      };
    } catch (error) {
      this.logger.error('Crisis response delivery failed', {
        error: error.message,
        waxId,
      });

      // Try fallback methods
      try {
        if (this.emailService) {
          await this.emailService.send({
            to: /* get from student profile */,
            subject: 'WaxPrep Crisis Support',
            text: text,
          });

          return { success: true, method: 'email' };
        }
      } catch (fallbackError) {
        this.logger.error('Crisis email fallback failed', {
          error: fallbackError.message,
        });
      }

      // If all delivery methods fail, log as critical
      this.logger.critical('All crisis response delivery methods failed', {
        waxId,
        sessionId,
      });

      return {
        success: false,
        method: 'failed',
        error: error.message,
      };
    }
  }

  /**
   * Notify operator of crisis
   */
  async notifyOperator({ waxId, sessionId, safetyEventId, urgency }) {
    const notification = {
      type: 'crisis_alert',
      urgency,
      waxId,
      sessionId,
      safetyEventId,
      timestamp: new Date().toISOString(),
    };

    let notified = false;

    // Try email
    if (config.OPERATOR_ALERT_EMAIL && this.emailService) {
      try {
        await this.emailService.send({
          to: config.OPERATOR_ALERT_EMAIL,
          subject: `[${urgency}] WaxPrep Crisis Alert`,
          text: `Crisis alert for student ${waxId}.\n\nEvent ID: ${safetyEventId}\nTime: ${new Date().toISOString()}`,
        });
        notified = true;
      } catch (error) {
        this.logger.error('Crisis email notification failed', {
          error: error.message,
        });
      }
    }

    // Try webhook
    if (config.OPERATOR_ALERT_WEBHOOK_URL && this.webhookService) {
      try {
        await this.webhookService.post(config.OPERATOR_ALERT_WEBHOOK_URL, {
          crisis_alert: notification,
        });
        notified = true;
      } catch (error) {
        this.logger.error('Crisis webhook notification failed', {
          error: error.message,
        });
      }
    }

    return {
      notified,
      methods: {
        email: !!config.OPERATOR_ALERT_EMAIL,
        webhook: !!config.OPERATOR_ALERT_WEBHOOK_URL,
      },
    };
  }

  /**
   * Log crisis response to database
   */
  async logCrisisResponse({
    waxId,
    sessionId,
    aiRequestId,
    safetyEventId,
    level,
    responseText,
    deliveredVia,
    operatorNotified = false,
  }) {
    try {
      await this.db.query(
        `INSERT INTO crisis_responses (
          safety_event_id, response_version, delivered_via,
          operator_notified_at, operator_notification_method
        ) VALUES ($1, $2, $3, $4, $5)`,
        [
          safetyEventId,
          'v1',
          deliveredVia,
          operatorNotified ? new Date() : null,
          operatorNotified ? 'email' : null,
        ]
      );
    } catch (error) {
      this.logger.error('Failed to log crisis response', {
        error: error.message,
      });
    }
  }

  /**
   * Send message via WhatsApp
   */
  async sendViaWhatsApp({ waxId, message }) {
    // This would integrate with the WhatsApp messaging layer
    // For now, return a mock result
    return {
      success: true,
      messageId: `crisis_${Date.now()}_${waxId}`,
    };
  }

  /**
   * Check if a student has had recent crisis alerts
   */
  async getRecentCrisisCount(waxId, hours = 24) {
    try {
      const cutoff = new Date(Date.now() - hours * 60 * 60 * 1000);

      const result = await this.db.query(
        `SELECT COUNT(*) as count
         FROM safety_events
         WHERE wax_id = $1
         AND event_type = 'crisis'
         AND created_at > $2`,
        [waxId, cutoff]
      );

      return parseInt(result.rows[0].count, 10);
    } catch (error) {
      this.logger.error('Failed to get recent crisis count', {
        error: error.message,
      });
      return 0;
    }
  }
}

/**
 * Get the deterministic crisis response text
 * Used by the AI orchestrator to inject into responses
 */
export function getCrisisResponseText() {
  return CRISIS_RESPONSE_TEXT;
}

export default CrisisProtocol;
