/**
 * Crisis Protocol - Phase I Stage 46
 * 
 * Deterministic crisis response delivery.
 * 
 * Architecture: Independent detection layer operating in parallel with tutor.
 * 
 * VERA-MH Framework: Target 0.81 clinician alignment. Err toward high recall
 * (accept false positives). False negatives are catastrophic.
 * 
 * Three-Level Response Protocol:
 * - Level 1: Academic Crisis Mention - No action. AI handles naturally.
 * - Level 2: Ambiguous Welfare Signal - Soft check-in.
 * - Level 3: High-Confidence Crisis - DETERMINISTIC response (not AI-generated).
 */

import config from '../config/index.js';

/**
 * Crisis response levels
 */
export const CrisisLevel = {
  LEVEL_1_ACADEMIC: 1,
  LEVEL_2_AMBIGUOUS: 2,
  LEVEL_3_CRISIS: 3,
};

/**
 * Deterministic crisis response text (NOT AI-generated)
 */
const CRISIS_RESPONSE_TEXT = config.SAFETY_CRISIS_RESPONSE_TEXT;

/**
 * Crisis protocol class
 */
export class CrisisProtocol {
  constructor({ db, logger, emailService = null, webhookService = null }) {
    this.db = db;
    this.logger = logger;
    this.emailService = emailService;
    this.webhookService = webhookService;
  }

  /**
   * Handle a crisis detection.
   *
   * @param {Object} params
   * @param {string} params.waxId - Student identifier.
   * @param {string} params.sessionId - Session identifier.
   * @param {string} [params.aiRequestId] - AI request ID (for audit trail).
   * @param {number} params.level - 1, 2, or 3 (CrisisLevel).
   * @param {string} [params.safetyEventId] - Safety event ID.
   * @param {string} [params.phoneNumber] - Student's phone number (in-memory only,
   *   never persisted). Required to actually deliver a WhatsApp message.
   *   If absent, the crisis response is recorded but not delivered.
   * @param {string} [params.triggerContent] - The student's message that triggered
   *   the crisis detection (for audit, never persisted as raw content).
   */
  async handleCrisis({ waxId, sessionId, aiRequestId, level, safetyEventId, phoneNumber, triggerContent }) {
    switch (level) {
      case CrisisLevel.LEVEL_1_ACADEMIC:
        return await this.handleLevel1({ waxId, sessionId });

      case CrisisLevel.LEVEL_2_AMBIGUOUS:
        return await this.handleLevel2({ waxId, sessionId, aiRequestId, phoneNumber });

      case CrisisLevel.LEVEL_3_CRISIS:
        return await this.handleLevel3({
          waxId,
          sessionId,
          aiRequestId,
          safetyEventId,
          phoneNumber,
          triggerContent,
        });

      default:
        return { handled: false, reason: 'Unknown crisis level' };
    }
  }

  /**
   * Level 1: Academic mention - no action needed
   */
  async handleLevel1({ waxId, sessionId }) {
    return {
      level: CrisisLevel.LEVEL_1_ACADEMIC,
      action: 'none',
      message: 'Academic mention - no action required',
      crisisResponseDelivered: false,
      operatorNotified: false,
    };
  }

  /**
   * Level 2: Ambiguous welfare signal - soft check-in.
   *
   * If phoneNumber is provided, actually deliver the check-in via WhatsApp.
   * If not, log it but don't deliver (operator must intervene manually).
   */
  async handleLevel2({ waxId, sessionId, aiRequestId, phoneNumber }) {
    const checkInMessage =
      'School can be stressful. If you ever want to talk about something difficult, we are here to listen.';

    let delivered = false;
    let deliveryMethod = 'none';

    if (phoneNumber) {
      try {
        await this.sendViaWhatsApp({ waxId, phoneNumber, message: checkInMessage });
        delivered = true;
        deliveryMethod = 'whatsapp';
      } catch (err) {
        this.logger.error('Level 2 check-in delivery failed', { error: err.message, waxId });
        deliveryMethod = 'failed';
      }
    }

    await this.logCrisisResponse({
      waxId,
      sessionId,
      aiRequestId,
      level: CrisisLevel.LEVEL_2_AMBIGUOUS,
      responseText: checkInMessage,
      deliveredVia: deliveryMethod,
    });

    return {
      level: CrisisLevel.LEVEL_2_AMBIGUOUS,
      action: 'soft_checkin',
      message: checkInMessage,
      crisisResponseDelivered: delivered,
      operatorNotified: false,
    };
  }

  /**
   * Level 3: High-confidence crisis - DETERMINISTIC response.
   *
   * This is NOT generated by AI. It is a hardcoded, human-reviewed
   * crisis response that must be delivered regardless of AI state.
   *
   * @param {Object} params
   * @param {string} params.phoneNumber - Required for actual delivery.
   *   If absent, the crisis response is recorded with delivery_status='failed'
   *   so an operator can intervene.
   */
  async handleLevel3({ waxId, sessionId, aiRequestId, safetyEventId, phoneNumber, triggerContent }) {
    // 1. Deliver deterministic crisis response.
    const deliverResult = await this.deliverCrisisResponse({
      waxId,
      sessionId,
      aiRequestId,
      phoneNumber,
      text: CRISIS_RESPONSE_TEXT,
    });

    // 2. Notify operator immediately.
    const notifyResult = await this.notifyOperator({
      waxId,
      sessionId,
      safetyEventId,
      urgency: 'high',
      // Include trigger content for the operator's eyes only — never persisted
      // to the audit log because triggerContent may be sensitive.
      triggerContent: triggerContent ? triggerContent.slice(0, 500) : null,
    });

    // 3. Log the crisis response.
    await this.logCrisisResponse({
      waxId,
      sessionId,
      aiRequestId,
      safetyEventId,
      level: CrisisLevel.LEVEL_3_CRISIS,
      responseText: CRISIS_RESPONSE_TEXT,
      deliveredVia: deliverResult.method,
      deliverySuccess: deliverResult.success,
      operatorNotified: notifyResult.notified,
    });

    return {
      level: CrisisLevel.LEVEL_3_CRISIS,
      action: 'crisis_response_delivered',
      message: CRISIS_RESPONSE_TEXT,
      content: CRISIS_RESPONSE_TEXT, // Worker reads `response.content` for delivery.
      crisisResponseDelivered: deliverResult.success,
      deliveryMethod: deliverResult.method,
      operatorNotified: notifyResult.notified,
      notifyResult,
    };
  }

  /**
   * Deliver deterministic crisis response
   * 
   * CRITICAL: This is infrastructure-level, not AI-generated.
   * Must succeed even if AI or DB is down.
   */
  /**
   * Deliver deterministic crisis response via WhatsApp Cloud API.
   *
   * If phoneNumber is provided, performs the actual HTTP send.
   * If phoneNumber is absent (legacy caller), records the attempt as
   * 'failed' so an operator can intervene.
   */
  async deliverCrisisResponse({ waxId, sessionId, aiRequestId, phoneNumber, text }) {
    if (!phoneNumber) {
      // Without the phone number we cannot deliver. Persist an audit row
      // so the operator can see the crisis was detected but not delivered.
      try {
        await this.db.query(
          `INSERT INTO outbound_messages
             (outbound_chunk_id, wax_id, triggering_message_id, content, processing_status, delivery_attempts, error_message, created_at)
           VALUES ($1, $2, NULL, $3, 'failed', 0, 'No phone number in crisis context', NOW())
           ON CONFLICT (outbound_chunk_id) DO NOTHING`,
          [`crisis:${waxId}:${Date.now()}`, waxId],
        );
      } catch (persistErr) {
        this.logger.error('Failed to persist crisis failed-delivery audit', { error: persistErr.message });
      }
      return { success: false, method: 'failed', error: 'phone_number_required' };
    }

    try {
      const result = await this.sendViaWhatsApp({ waxId, phoneNumber, message: text });
      return {
        success: result.success,
        method: 'whatsapp',
        messageId: result.messageId,
      };
    } catch (error) {
      this.logger.error('Crisis response delivery failed', {
        error: error.message,
        waxId,
      });
      return { success: false, method: 'failed', error: error.message };
    }
  }

  /**
   * Notify operator of crisis
   */
  async notifyOperator({ waxId, sessionId, safetyEventId, urgency }) {
    const notification = {
      type: 'crisis_alert',
      urgency,
      waxId,
      sessionId,
      safetyEventId,
      timestamp: new Date().toISOString(),
    };

    let notified = false;

    // Try email
    if (config.OPERATOR_ALERT_EMAIL && this.emailService) {
      try {
        await this.emailService.send({
          to: config.OPERATOR_ALERT_EMAIL,
          subject: `[${urgency}] WaxPrep Crisis Alert`,
          text: `Crisis alert for student ${waxId}.\n\nEvent ID: ${safetyEventId}\nTime: ${new Date().toISOString()}`,
        });
        notified = true;
      } catch (error) {
        this.logger.error('Crisis email notification failed', {
          error: error.message,
        });
      }
    }

    // Try webhook
    if (config.OPERATOR_ALERT_WEBHOOK_URL && this.webhookService) {
      try {
        await this.webhookService.post(config.OPERATOR_ALERT_WEBHOOK_URL, {
          crisis_alert: notification,
        });
        notified = true;
      } catch (error) {
        this.logger.error('Crisis webhook notification failed', {
          error: error.message,
        });
      }
    }

    return {
      notified,
      methods: {
        email: !!config.OPERATOR_ALERT_EMAIL,
        webhook: !!config.OPERATOR_ALERT_WEBHOOK_URL,
      },
    };
  }

  /**
   * Log crisis response to database
   */
  async logCrisisResponse({
    waxId,
    sessionId,
    aiRequestId,
    safetyEventId,
    level,
    responseText,
    deliveredVia,
    operatorNotified = false,
  }) {
    try {
      await this.db.query(
        `INSERT INTO crisis_responses (
          safety_event_id, response_version, delivered_via,
          operator_notified_at, operator_notification_method
        ) VALUES ($1, $2, $3, $4, $5)`,
        [
          safetyEventId,
          'v1',
          deliveredVia,
          operatorNotified ? new Date() : null,
          operatorNotified ? 'email' : null,
        ],
      );
    } catch (error) {
      this.logger.error('Failed to log crisis response', {
        error: error.message,
      });
    }
  }

  /**
   * Send a crisis-response message via WhatsApp Cloud API.
   *
   * Uses the same config as src/messaging/outbound.js (WHATSAPP_ACCESS_TOKEN,
   * WHATSAPP_PHONE_NUMBER_ID). The phone number is passed in-memory from the
   * webhook context — it is NEVER persisted (only the irreversible hash is).
   */
  async sendViaWhatsApp({ waxId, phoneNumber, message }) {
    if (!phoneNumber) {
      throw new Error('sendViaWhatsApp: phoneNumber is required');
    }
    if (!config.WHATSAPP_ACCESS_TOKEN) {
      throw new Error('WHATSAPP_ACCESS_TOKEN is not configured — cannot deliver crisis response');
    }

    const url = `${config.WHATSAPP_API_BASE_URL}/${config.WHATSAPP_API_VERSION}/${config.WHATSAPP_PHONE_NUMBER_ID}/messages`;
    const body = {
      messaging_product: 'whatsapp',
      to: phoneNumber,
      type: 'text',
      text: { body: message, preview_url: false },
    };

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${config.WHATSAPP_ACCESS_TOKEN}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(10000),
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      // Persist a failed-delivery audit row so the operator sees the crisis was attempted.
      try {
        await this.db.query(
          `INSERT INTO outbound_messages
             (outbound_chunk_id, wax_id, triggering_message_id, content, processing_status, delivery_attempts, error_message, created_at)
           VALUES ($1, $2, NULL, $3, 'failed', 1, $4, NOW())
           ON CONFLICT (outbound_chunk_id) DO NOTHING`,
          [`crisis:${waxId}:${Date.now()}`, waxId, message, `WhatsApp API ${response.status}: ${errText.slice(0, 200)}`],
        );
      } catch (persistErr) {
        this.logger.error('Failed to persist crisis failed-delivery audit', { error: persistErr.message });
      }
      throw new Error(`WhatsApp API error: ${response.status}`);
    }

    const data = await response.json().catch(() => ({}));
    const messageId = data?.messages?.[0]?.id;

    // Persist the sent audit row.
    try {
      await this.db.query(
        `INSERT INTO outbound_messages
           (outbound_chunk_id, wax_id, triggering_message_id, content, processing_status, sent_at, external_message_id, created_at)
         VALUES ($1, $2, NULL, $3, 'sent', NOW(), $4, NOW())
         ON CONFLICT (outbound_chunk_id) DO NOTHING`,
        [`crisis:${waxId}:${messageId || Date.now()}`, waxId, message, messageId],
      );
    } catch (persistErr) {
      this.logger.error('Failed to persist crisis sent-delivery audit', { error: persistErr.message });
    }

    return { success: true, messageId };
  }

  /**
   * Check if a student has had recent crisis alerts
   */
  async getRecentCrisisCount(waxId, hours = 24) {
    try {
      const cutoff = new Date(Date.now() - hours * 60 * 60 * 1000);

      const result = await this.db.query(
        `SELECT COUNT(*) as count
         FROM safety_events
         WHERE wax_id = $1
         AND event_type = 'crisis'
         AND created_at > $2`,
        [waxId, cutoff],
      );

      return parseInt(result.rows[0].count, 10);
    } catch (error) {
      this.logger.error('Failed to get recent crisis count', {
        error: error.message,
      });
      return 0;
    }
  }
}

/**
 * Get the deterministic crisis response text
 * Used by the AI orchestrator to inject into responses
 */
export function getCrisisResponseText() {
  return CRISIS_RESPONSE_TEXT;
}

export default CrisisProtocol;
